#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN {
    unshift @INC, "$FindBin::Bin/../lib";
    $ENV{MOJO_HOME} = $FindBin::Bin
      unless $ENV{MOJO_HOME};
}
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('ImportCsv');
